### ISSUE TITLE
"Arrays chunk sizes are unknown:"

### ISSUE THREAD

**Issue by jbednar** [holoviz/holoviz#140]
```
$~/pyviz/examples/tutorial/apps> pyver bokeh geoviews holoviews dask pandas datashader
bokeh=1.0.0                    # ~/anaconda/envs/pyviz/lib/python3.6/site-packages/bokeh
geoviews=1.6.0a3.post4+g6fa50ac # ~/geoviews/geoviews
holoviews=1.11.0a11.post47+gb1e614b # ~/holoviews_git/holoviews
dask=0.18.2                    # ~/anaconda/envs/pyviz/lib/python3.6/site-packages/dask
pandas=0.22.0                  # ~/anaconda/envs/pyviz/lib/python3.6/site-packages/pandas
datashader=0.6.9a1.post1+g174e5bd # /Users/jbednar/datashader_git_moved/datashader
$~/pyviz/examples/tutorial/apps> bokeh serve --show nyc_taxi
2018-12-14 13:07:51,554 Starting Bokeh server version 1.0.0 (running on Tornado 4.5.3)
2018-12-14 13:07:51,559 Bokeh app running at: http://localhost:5006/nyc_taxi
2018-12-14 13:07:51,559 Starting Bokeh server with process id: 5902
--- Logging error ---
Traceback (most recent call last):
  File "~/holoviews_git/holoviews/core/spaces.py", line 766, in __call__
    ret = self.callable(*args, **kwargs)
  File "~/holoviews_git/holoviews/util/__init__.py", line 782, in dynamic_operation
    return self._process(map_obj[key], key)
  File "~/holoviews_git/holoviews/util/__init__.py", line 764, in _process
    return self.p.operation.process_element(element, key, **kwargs)
  File "~/holoviews_git/holoviews/core/operation.py", line 143, in process_element
    return self._apply(element, key)
  File "~/holoviews_git/holoviews/core/operation.py", line 121, in _apply
    ret = self._process(element, key)
  File "~/holoviews_git/holoviews/operation/datashader.py", line 819, in _process
    element = element.map(op, predicate)
  File "~/holoviews_git/holoviews/core/dimension.py", line 826, in map
    return map_fn(self) if applies else self
  File "~/holoviews_git/holoviews/core/operation.py", line 163, in __call__
    processed = self._apply(element)
  File "~/holoviews_git/holoviews/core/operation.py", line 121, in _apply
    ret = self._process(element, key)
  File "~/holoviews_git/holoviews/operation/datashader.py", line 437, in _process
    x, y, data, glyph = self.get_agg_data(element, category)
  File "~/holoviews_git/holoviews/operation/datashader.py", line 327, in get_agg_data
    for d in (x, y)):
  File "~/holoviews_git/holoviews/operation/datashader.py", line 327, in <genexpr>
    for d in (x, y)):
  File "~/anaconda/envs/pyviz/lib/python3.6/site-packages/dask/array/core.py", line 1383, in __getitem__
    dsk, chunks = slice_array(out, self.name, self.chunks, index2)
  File "~/anaconda/envs/pyviz/lib/python3.6/site-packages/dask/array/slicing.py", line 158, in slice_array
    dsk_out, bd_out = slice_with_newaxes(out_name, in_name, blockdims, index)
  File "~/anaconda/envs/pyviz/lib/python3.6/site-packages/dask/array/slicing.py", line 180, in slice_with_newaxes
    dsk, blockdims2 = slice_wrap_lists(out_name, in_name, blockdims, index2)
  File "~/anaconda/envs/pyviz/lib/python3.6/site-packages/dask/array/slicing.py", line 235, in slice_wrap_lists
    return slice_slices_and_integers(out_name, in_name, blockdims, index)
  File "~/anaconda/envs/pyviz/lib/python3.6/site-packages/dask/array/slicing.py", line 280, in slice_slices_and_integers
    raise ValueError("Arrays chunk sizes are unknown: %s", shape)
ValueError: ('Arrays chunk sizes are unknown: %s', (nan,))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "~/anaconda/envs/pyviz/lib/python3.6/logging/__init__.py", line 993, in emit
    msg = self.format(record)
  File "~/anaconda/envs/pyviz/lib/python3.6/logging/__init__.py", line 839, in format
    return fmt.format(record)
  File "~/anaconda/envs/pyviz/lib/python3.6/logging/__init__.py", line 576, in format
    record.message = record.getMessage()
  File "~/anaconda/envs/pyviz/lib/python3.6/logging/__init__.py", line 338, in getMessage
    msg = msg % self.args
TypeError: not enough arguments for format string
Call stack:
  File "~/anaconda/envs/pyviz/bin/bokeh", line 10, in <module>
    sys.exit(main())
  File "~/anaconda/envs/pyviz/lib/python3.6/site-packages/bokeh/__main__.py", line 65, in main
    _main(sys.argv)
  File "~/anaconda/envs/pyviz/lib/python3.6/site-packages/bokeh/command/bootstrap.py", line 114, in main
    args.invoke(args)
  File "~/anaconda/envs/pyviz/lib/python3.6/site-packages/bokeh/command/subcommands/serve.py", line 652, in invoke
    server.run_until_shutdown()
  File "~/anaconda/envs/pyviz/lib/python3.6/site-packages/bokeh/server/server.py", line 204, in run_until_shutdown
    self._loop.start()
  File "~/anaconda/envs/pyviz/lib/python3.6/site-packages/tornado/ioloop.py", line 888, in start
    handler_func(fd_obj, events)
  File "~/anaconda/envs/pyviz/lib/python3.6/site-packages/tornado/stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "~/anaconda/envs/pyviz/lib/python3.6/site-packages/tornado/netutil.py", line 277, in accept_handler
    callback(connection, address)
  File "~/anaconda/envs/pyviz/lib/python3.6/site-packages/tornado/tcpserver.py", line 295, in _handle_connection
    future = self.handle_stream(stream, address)
  File "~/anaconda/envs/pyviz/lib/python3.6/site-packages/tornado/httpserver.py", line 193, in handle_stream
    conn.start_serving(self)
  File "~/anaconda/envs/pyviz/lib/python3.6/site-packages/tornado/http1connection.py", line 713, in start_serving
    self._serving_future = self._server_request_loop(delegate)
  File "~/anaconda/envs/pyviz/lib/python3.6/site-packages/tornado/gen.py", line 307, in wrapper
    yielded = next(result)
  File "~/anaconda/envs/pyviz/lib/python3.6/site-packages/tornado/http1connection.py", line 726, in _server_request_loop
    ret = yield conn.read_response(request_delegate)
  File "~/anaconda/envs/pyviz/lib/python3.6/site-packages/tornado/http1connection.py", line 151, in read_response
    return self._read_message(delegate)
  File "~/anaconda/envs/pyviz/lib/python3.6/site-packages/tornado/gen.py", line 319, in wrapper
    _futures_to_runners[future] = Runner(result, future, yielded)
  File "~/anaconda/envs/pyviz/lib/python3.6/site-packages/tornado/gen.py", line 1003, in __init__
    self.run()
  File "~/anaconda/envs/pyviz/lib/python3.6/site-packages/tornado/gen.py", line 1069, in run
    yielded = self.gen.send(value)
  File "~/anaconda/envs/pyviz/lib/python3.6/site-packages/tornado/http1connection.py", line 238, in _read_message
    delegate.finish()
  File "~/anaconda/envs/pyviz/lib/python3.6/site-packages/tornado/routing.py", line 251, in finish
    self.delegate.finish()
  File "~/anaconda/envs/pyviz/lib/python3.6/site-packages/tornado/web.py", line 2097, in finish
    self.execute()
  File "~/anaconda/envs/pyviz/lib/python3.6/site-packages/tornado/web.py", line 2130, in execute
    **self.path_kwargs)
  File "~/anaconda/envs/pyviz/lib/python3.6/site-packages/tornado/gen.py", line 307, in wrapper
    yielded = next(result)
  File "~/anaconda/envs/pyviz/lib/python3.6/site-packages/tornado/web.py", line 1510, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "~/anaconda/envs/pyviz/lib/python3.6/site-packages/tornado/gen.py", line 307, in wrapper
    yielded = next(result)
  File "~/anaconda/envs/pyviz/lib/python3.6/site-packages/bokeh/server/views/doc_handler.py", line 21, in get
    session = yield self.get_session()
  File "~/anaconda/envs/pyviz/lib/python3.6/site-packages/tornado/gen.py", line 307, in wrapper
    yielded = next(result)
  File "~/anaconda/envs/pyviz/lib/python3.6/site-packages/bokeh/server/views/session_handler.py", line 43, in get_session
    session = yield self.application_context.create_session_if_needed(session_id, self.request)
  File "~/anaconda/envs/pyviz/lib/python3.6/site-packages/tornado/gen.py", line 319, in wrapper
    _futures_to_runners[future] = Runner(result, future, yielded)
  File "~/anaconda/envs/pyviz/lib/python3.6/site-packages/tornado/gen.py", line 1003, in __init__
    self.run()
  File "~/anaconda/envs/pyviz/lib/python3.6/site-packages/tornado/gen.py", line 1069, in run
    yielded = self.gen.send(value)
  File "~/anaconda/envs/pyviz/lib/python3.6/site-packages/bokeh/server/contexts.py", line 185, in create_session_if_needed
    self._application.initialize_document(doc)
  File "~/anaconda/envs/pyviz/lib/python3.6/site-packages/bokeh/application/application.py", line 179, in initialize_document
    h.modify_document(doc)
  File "~/anaconda/envs/pyviz/lib/python3.6/site-packages/bokeh/application/handlers/directory.py", line 191, in modify_document
    self._main_handler.modify_document(doc)
  File "~/anaconda/envs/pyviz/lib/python3.6/site-packages/bokeh/application/handlers/code.py", line 172, in modify_document
    self._runner.run(module, post_check)
  File "~/anaconda/envs/pyviz/lib/python3.6/site-packages/bokeh/application/handlers/code_runner.py", line 180, in run
    exec(self._code, module.__dict__)
  File "~/pyviz/examples/tutorial/apps/nyc_taxi/main.py", line 40, in <module>
    pn.Row(taxi.param, taxi.view()).servable()
  File "~/panel/panel/viewable.py", line 163, in servable
    self.server_doc()
  File "~/panel/panel/viewable.py", line 150, in server_doc
    model = self._get_root(doc)
  File "~/panel/panel/viewable.py", line 86, in _get_root
    root = self._get_model(doc, comm=comm)
  File "~/panel/panel/layout.py", line 132, in _get_model
    objects = self._get_objects(model, [], doc, root, comm)
  File "~/panel/panel/layout.py", line 125, in _get_objects
    child = pane._get_model(doc, root, model, comm)
  File "~/panel/panel/holoviews.py", line 114, in _get_model
    plot = self._render(doc, comm, root)
  File "~/panel/panel/holoviews.py", line 100, in _render
    plot = renderer.get_plot(self.object, **kwargs)
  File "~/holoviews_git/holoviews/plotting/bokeh/renderer.py", line 163, in get_plot
    plot = super(BokehRenderer, self_or_cls).get_plot(obj, renderer, **kwargs)
  File "~/holoviews_git/holoviews/plotting/renderer.py", line 186, in get_plot
    initialize_dynamic(obj)
  File "~/holoviews_git/holoviews/plotting/util.py", line 248, in initialize_dynamic
    dmap[dmap._initial_key()]
  File "~/holoviews_git/holoviews/core/spaces.py", line 1415, in __getitem__
    val = self._execute_callback(*tuple_key)
  File "~/holoviews_git/holoviews/core/spaces.py", line 1127, in _execute_callback
    retval = self.callback(*args, **kwargs)
  File "~/holoviews_git/holoviews/core/spaces.py", line 736, in __call__
    if not args and not kwargs and not any(kwarg_hash): return self.callable()
  File "~/holoviews_git/holoviews/core/spaces.py", line 261, in dynamic_mul
    other_el = other.select(HoloMap, **key_map) if other.kdims else other[()]
  File "~/holoviews_git/holoviews/core/spaces.py", line 1415, in __getitem__
    val = self._execute_callback(*tuple_key)
  File "~/holoviews_git/holoviews/core/spaces.py", line 1127, in _execute_callback
    retval = self.callback(*args, **kwargs)
  File "~/holoviews_git/holoviews/core/spaces.py", line 766, in __call__
    ret = self.callable(*args, **kwargs)
  File "~/holoviews_git/holoviews/util/__init__.py", line 782, in dynamic_operation
    return self._process(map_obj[key], key)
  File "~/holoviews_git/holoviews/core/spaces.py", line 1415, in __getitem__
    val = self._execute_callback(*tuple_key)
  File "~/holoviews_git/holoviews/core/spaces.py", line 1127, in _execute_callback
    retval = self.callback(*args, **kwargs)
  File "~/holoviews_git/holoviews/core/spaces.py", line 777, in __call__
    self.warning(message.format(name=self.name, argstr=argstr, e=repr(e)))
  File "~/anaconda/envs/pyviz/lib/python3.6/site-packages/param/parameterized.py", line 866, in inner
    return fn(*args, **kwargs)
  File "~/anaconda/envs/pyviz/lib/python3.6/site-packages/param/parameterized.py", line 2171, in warning
    return self.param.warning(msg,*args,**kw)
  File "~/anaconda/envs/pyviz/lib/python3.6/site-packages/param/parameterized.py", line 1378, in warning
    self_.__db_print(WARNING,msg,*args,**kw)
  File "~/anaconda/envs/pyviz/lib/python3.6/site-packages/param/parameterized.py", line 1359, in __db_print
    get_logger().log(level, '%s%s: '+msg, prefix, self_or_cls.name, *args, **kw)
Message: '%s%s: Callable raised "ValueError(\'Arrays chunk sizes are unknown: %s\', (nan,))".\nInvoked as dynamic_operation(height=400, scale=1.0, width=600, x_range=None, y_range=None)'
Arguments: ('', 'dynamic_operation')
--- Logging error ---
Traceback (most recent call last):
  File "~/holoviews_git/holoviews/core/spaces.py", line 766, in __call__
    ret = self.callable(*args, **kwargs)
  File "~/holoviews_git/holoviews/util/__init__.py", line 782, in dynamic_operation
    return self._process(map_obj[key], key)
  File "~/holoviews_git/holoviews/core/spaces.py", line 1415, in __getitem__
    val = self._execute_callback(*tuple_key)
  File "~/holoviews_git/holoviews/core/spaces.py", line 1127, in _execute_callback
    retval = self.callback(*args, **kwargs)
  File "~/holoviews_git/holoviews/core/spaces.py", line 766, in __call__
    ret = self.callable(*args, **kwargs)
  File "~/holoviews_git/holoviews/util/__init__.py", line 782, in dynamic_operation
    return self._process(map_obj[key], key)
  File "~/holoviews_git/holoviews/util/__init__.py", line 764, in _process
    return self.p.operation.process_element(element, key, **kwargs)
  File "~/holoviews_git/holoviews/core/operation.py", line 143, in process_element
    return self._apply(element, key)
  File "~/holoviews_git/holoviews/core/operation.py", line 121, in _apply
    ret = self._process(element, key)
  File "~/holoviews_git/holoviews/operation/datashader.py", line 819, in _process
    element = element.map(op, predicate)
  File "~/holoviews_git/holoviews/core/dimension.py", line 826, in map
    return map_fn(self) if applies else self
  File "~/holoviews_git/holoviews/core/operation.py", line 163, in __call__
    processed = self._apply(element)
  File "~/holoviews_git/holoviews/core/operation.py", line 121, in _apply
    ret = self._process(element, key)
  File "~/holoviews_git/holoviews/operation/datashader.py", line 437, in _process
    x, y, data, glyph = self.get_agg_data(element, category)
  File "~/holoviews_git/holoviews/operation/datashader.py", line 327, in get_agg_data
    for d in (x, y)):
  File "~/holoviews_git/holoviews/operation/datashader.py", line 327, in <genexpr>
    for d in (x, y)):
  File "~/anaconda/envs/pyviz/lib/python3.6/site-packages/dask/array/core.py", line 1383, in __getitem__
    dsk, chunks = slice_array(out, self.name, self.chunks, index2)
  File "~/anaconda/envs/pyviz/lib/python3.6/site-packages/dask/array/slicing.py", line 158, in slice_array
    dsk_out, bd_out = slice_with_newaxes(out_name, in_name, blockdims, index)
  File "~/anaconda/envs/pyviz/lib/python3.6/site-packages/dask/array/slicing.py", line 180, in slice_with_newaxes
    dsk, blockdims2 = slice_wrap_lists(out_name, in_name, blockdims, index2)
  File "~/anaconda/envs/pyviz/lib/python3.6/site-packages/dask/array/slicing.py", line 235, in slice_wrap_lists
    return slice_slices_and_integers(out_name, in_name, blockdims, index)
  File "~/anaconda/envs/pyviz/lib/python3.6/site-packages/dask/array/slicing.py", line 280, in slice_slices_and_integers
    raise ValueError("Arrays chunk sizes are unknown: %s", shape)
ValueError: ('Arrays chunk sizes are unknown: %s', (nan,))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "~/anaconda/envs/pyviz/lib/python3.6/logging/__init__.py", line 993, in emit
    msg = self.format(record)
  File "~/anaconda/envs/pyviz/lib/python3.6/logging/__init__.py", line 839, in format
    return fmt.format(record)
  File "~/anaconda/envs/pyviz/lib/python3.6/logging/__init__.py", line 576, in format
    record.message = record.getMessage()
  File "~/anaconda/envs/pyviz/lib/python3.6/logging/__init__.py", line 338, in getMessage
    msg = msg % self.args
TypeError: not enough arguments for format string
Call stack:
  File "~/anaconda/envs/pyviz/bin/bokeh", line 10, in <module>
    sys.exit(main())
  File "~/anaconda/envs/pyviz/lib/python3.6/site-packages/bokeh/__main__.py", line 65, in main
    _main(sys.argv)
  File "~/anaconda/envs/pyviz/lib/python3.6/site-packages/bokeh/command/bootstrap.py", line 114, in main
    args.invoke(args)
  File "~/anaconda/envs/pyviz/lib/python3.6/site-packages/bokeh/command/subcommands/serve.py", line 652, in invoke
    server.run_until_shutdown()
  File "~/anaconda/envs/pyviz/lib/python3.6/site-packages/bokeh/server/server.py", line 204, in run_until_shutdown
    self._loop.start()
  File "~/anaconda/envs/pyviz/lib/python3.6/site-packages/tornado/ioloop.py", line 888, in start
    handler_func(fd_obj, events)
  File "~/anaconda/envs/pyviz/lib/python3.6/site-packages/tornado/stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "~/anaconda/envs/pyviz/lib/python3.6/site-packages/tornado/netutil.py", line 277, in accept_handler
    callback(connection, address)
  File "~/anaconda/envs/pyviz/lib/python3.6/site-packages/tornado/tcpserver.py", line 295, in _handle_connection
    future = self.handle_stream(stream, address)
  File "~/anaconda/envs/pyviz/lib/python3.6/site-packages/tornado/httpserver.py", line 193, in handle_stream
    conn.start_serving(self)
  File "~/anaconda/envs/pyviz/lib/python3.6/site-packages/tornado/http1connection.py", line 713, in start_serving
    self._serving_future = self._server_request_loop(delegate)
  File "~/anaconda/envs/pyviz/lib/python3.6/site-packages/tornado/gen.py", line 307, in wrapper
    yielded = next(result)
  File "~/anaconda/envs/pyviz/lib/python3.6/site-packages/tornado/http1connection.py", line 726, in _server_request_loop
    ret = yield conn.read_response(request_delegate)
  File "~/anaconda/envs/pyviz/lib/python3.6/site-packages/tornado/http1connection.py", line 151, in read_response
    return self._read_message(delegate)
  File "~/anaconda/envs/pyviz/lib/python3.6/site-packages/tornado/gen.py", line 319, in wrapper
    _futures_to_runners[future] = Runner(result, future, yielded)
  File "~/anaconda/envs/pyviz/lib/python3.6/site-packages/tornado/gen.py", line 1003, in __init__
    self.run()
  File "~/anaconda/envs/pyviz/lib/python3.6/site-packages/tornado/gen.py", line 1069, in run
    yielded = self.gen.send(value)
  File "~/anaconda/envs/pyviz/lib/python3.6/site-packages/tornado/http1connection.py", line 238, in _read_message
    delegate.finish()
  File "~/anaconda/envs/pyviz/lib/python3.6/site-packages/tornado/routing.py", line 251, in finish
    self.delegate.finish()
  File "~/anaconda/envs/pyviz/lib/python3.6/site-packages/tornado/web.py", line 2097, in finish
    self.execute()
  File "~/anaconda/envs/pyviz/lib/python3.6/site-packages/tornado/web.py", line 2130, in execute
    **self.path_kwargs)
  File "~/anaconda/envs/pyviz/lib/python3.6/site-packages/tornado/gen.py", line 307, in wrapper
    yielded = next(result)
  File "~/anaconda/envs/pyviz/lib/python3.6/site-packages/tornado/web.py", line 1510, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "~/anaconda/envs/pyviz/lib/python3.6/site-packages/tornado/gen.py", line 307, in wrapper
    yielded = next(result)
  File "~/anaconda/envs/pyviz/lib/python3.6/site-packages/bokeh/server/views/doc_handler.py", line 21, in get
    session = yield self.get_session()
  File "~/anaconda/envs/pyviz/lib/python3.6/site-packages/tornado/gen.py", line 307, in wrapper
    yielded = next(result)
  File "~/anaconda/envs/pyviz/lib/python3.6/site-packages/bokeh/server/views/session_handler.py", line 43, in get_session
    session = yield self.application_context.create_session_if_needed(session_id, self.request)
  File "~/anaconda/envs/pyviz/lib/python3.6/site-packages/tornado/gen.py", line 319, in wrapper
    _futures_to_runners[future] = Runner(result, future, yielded)
  File "~/anaconda/envs/pyviz/lib/python3.6/site-packages/tornado/gen.py", line 1003, in __init__
    self.run()
  File "~/anaconda/envs/pyviz/lib/python3.6/site-packages/tornado/gen.py", line 1069, in run
    yielded = self.gen.send(value)
  File "~/anaconda/envs/pyviz/lib/python3.6/site-packages/bokeh/server/contexts.py", line 185, in create_session_if_needed
    self._application.initialize_document(doc)
  File "~/anaconda/envs/pyviz/lib/python3.6/site-packages/bokeh/application/application.py", line 179, in initialize_document
    h.modify_document(doc)
  File "~/anaconda/envs/pyviz/lib/python3.6/site-packages/bokeh/application/handlers/directory.py", line 191, in modify_document
    self._main_handler.modify_document(doc)
  File "~/anaconda/envs/pyviz/lib/python3.6/site-packages/bokeh/application/handlers/code.py", line 172, in modify_document
    self._runner.run(module, post_check)
  File "~/anaconda/envs/pyviz/lib/python3.6/site-packages/bokeh/application/handlers/code_runner.py", line 180, in run
    exec(self._code, module.__dict__)
  File "~/pyviz/examples/tutorial/apps/nyc_taxi/main.py", line 40, in <module>
    pn.Row(taxi.param, taxi.view()).servable()
  File "~/panel/panel/viewable.py", line 163, in servable
    self.server_doc()
  File "~/panel/panel/viewable.py", line 150, in server_doc
    model = self._get_root(doc)
  File "~/panel/panel/viewable.py", line 86, in _get_root
    root = self._get_model(doc, comm=comm)
  File "~/panel/panel/layout.py", line 132, in _get_model
    objects = self._get_objects(model, [], doc, root, comm)
  File "~/panel/panel/layout.py", line 125, in _get_objects
    child = pane._get_model(doc, root, model, comm)
  File "~/panel/panel/holoviews.py", line 114, in _get_model
    plot = self._render(doc, comm, root)
  File "~/panel/panel/holoviews.py", line 100, in _render
    plot = renderer.get_plot(self.object, **kwargs)
  File "~/holoviews_git/holoviews/plotting/bokeh/renderer.py", line 163, in get_plot
    plot = super(BokehRenderer, self_or_cls).get_plot(obj, renderer, **kwargs)
  File "~/holoviews_git/holoviews/plotting/renderer.py", line 186, in get_plot
    initialize_dynamic(obj)
  File "~/holoviews_git/holoviews/plotting/util.py", line 248, in initialize_dynamic
    dmap[dmap._initial_key()]
  File "~/holoviews_git/holoviews/core/spaces.py", line 1415, in __getitem__
    val = self._execute_callback(*tuple_key)
  File "~/holoviews_git/holoviews/core/spaces.py", line 1127, in _execute_callback
    retval = self.callback(*args, **kwargs)
  File "~/holoviews_git/holoviews/core/spaces.py", line 736, in __call__
    if not args and not kwargs and not any(kwarg_hash): return self.callable()
  File "~/holoviews_git/holoviews/core/spaces.py", line 261, in dynamic_mul
    other_el = other.select(HoloMap, **key_map) if other.kdims else other[()]
  File "~/holoviews_git/holoviews/core/spaces.py", line 1415, in __getitem__
    val = self._execute_callback(*tuple_key)
  File "~/holoviews_git/holoviews/core/spaces.py", line 1127, in _execute_callback
    retval = self.callback(*args, **kwargs)
  File "~/holoviews_git/holoviews/core/spaces.py", line 777, in __call__
    self.warning(message.format(name=self.name, argstr=argstr, e=repr(e)))
  File "~/anaconda/envs/pyviz/lib/python3.6/site-packages/param/parameterized.py", line 866, in inner
    return fn(*args, **kwargs)
  File "~/anaconda/envs/pyviz/lib/python3.6/site-packages/param/parameterized.py", line 2171, in warning
    return self.param.warning(msg,*args,**kw)
  File "~/anaconda/envs/pyviz/lib/python3.6/site-packages/param/parameterized.py", line 1378, in warning
    self_.__db_print(WARNING,msg,*args,**kw)
  File "~/anaconda/envs/pyviz/lib/python3.6/site-packages/param/parameterized.py", line 1359, in __db_print
    get_logger().log(level, '%s%s: '+msg, prefix, self_or_cls.name, *args, **kw)
Message: '%s%s: Callable raised "ValueError(\'Arrays chunk sizes are unknown: %s\', (nan,))".\nInvoked as dynamic_operation(cmap=<matplotlib.colors.LinearSegmentedColormap object at 0x1c208c55c0>)'
Arguments: ('', 'dynamic_operation')
2018-12-14 13:08:01,825 Error running application handler <bokeh.application.handlers.directory.DirectoryHandler object at 0x1113d0d30>: ('Arrays chunk sizes are unknown: %s', (nan,))
File "slicing.py", line 280, in slice_slices_and_integers:
raise ValueError("Arrays chunk sizes are unknown: %s", shape) Traceback (most recent call last):
  File "~/anaconda/envs/pyviz/lib/python3.6/site-packages/bokeh/application/handlers/code_runner.py", line 180, in run
    exec(self._code, module.__dict__)
  File "~/pyviz/examples/tutorial/apps/nyc_taxi/main.py", line 40, in <module>
    pn.Row(taxi.param, taxi.view()).servable()
  File "~/panel/panel/viewable.py", line 163, in servable
    self.server_doc()
  File "~/panel/panel/viewable.py", line 150, in server_doc
    model = self._get_root(doc)
  File "~/panel/panel/viewable.py", line 86, in _get_root
    root = self._get_model(doc, comm=comm)
  File "~/panel/panel/layout.py", line 132, in _get_model
    objects = self._get_objects(model, [], doc, root, comm)
  File "~/panel/panel/layout.py", line 125, in _get_objects
    child = pane._get_model(doc, root, model, comm)
  File "~/panel/panel/holoviews.py", line 114, in _get_model
    plot = self._render(doc, comm, root)
  File "~/panel/panel/holoviews.py", line 100, in _render
    plot = renderer.get_plot(self.object, **kwargs)
  File "~/holoviews_git/holoviews/plotting/bokeh/renderer.py", line 163, in get_plot
    plot = super(BokehRenderer, self_or_cls).get_plot(obj, renderer, **kwargs)
  File "~/holoviews_git/holoviews/plotting/renderer.py", line 186, in get_plot
    initialize_dynamic(obj)
  File "~/holoviews_git/holoviews/plotting/util.py", line 248, in initialize_dynamic
    dmap[dmap._initial_key()]
  File "~/holoviews_git/holoviews/core/spaces.py", line 1415, in __getitem__
    val = self._execute_callback(*tuple_key)
  File "~/holoviews_git/holoviews/core/spaces.py", line 1127, in _execute_callback
    retval = self.callback(*args, **kwargs)
  File "~/holoviews_git/holoviews/core/spaces.py", line 736, in __call__
    if not args and not kwargs and not any(kwarg_hash): return self.callable()
  File "~/holoviews_git/holoviews/core/spaces.py", line 261, in dynamic_mul
    other_el = other.select(HoloMap, **key_map) if other.kdims else other[()]
  File "~/holoviews_git/holoviews/core/spaces.py", line 1415, in __getitem__
    val = self._execute_callback(*tuple_key)
  File "~/holoviews_git/holoviews/core/spaces.py", line 1127, in _execute_callback
    retval = self.callback(*args, **kwargs)
  File "~/holoviews_git/holoviews/core/spaces.py", line 766, in __call__
    ret = self.callable(*args, **kwargs)
  File "~/holoviews_git/holoviews/util/__init__.py", line 782, in dynamic_operation
    return self._process(map_obj[key], key)
  File "~/holoviews_git/holoviews/core/spaces.py", line 1415, in __getitem__
    val = self._execute_callback(*tuple_key)
  File "~/holoviews_git/holoviews/core/spaces.py", line 1127, in _execute_callback
    retval = self.callback(*args, **kwargs)
  File "~/holoviews_git/holoviews/core/spaces.py", line 766, in __call__
    ret = self.callable(*args, **kwargs)
  File "~/holoviews_git/holoviews/util/__init__.py", line 782, in dynamic_operation
    return self._process(map_obj[key], key)
  File "~/holoviews_git/holoviews/util/__init__.py", line 764, in _process
    return self.p.operation.process_element(element, key, **kwargs)
  File "~/holoviews_git/holoviews/core/operation.py", line 143, in process_element
    return self._apply(element, key)
  File "~/holoviews_git/holoviews/core/operation.py", line 121, in _apply
    ret = self._process(element, key)
  File "~/holoviews_git/holoviews/operation/datashader.py", line 819, in _process
    element = element.map(op, predicate)
  File "~/holoviews_git/holoviews/core/dimension.py", line 826, in map
    return map_fn(self) if applies else self
  File "~/holoviews_git/holoviews/core/operation.py", line 163, in __call__
    processed = self._apply(element)
  File "~/holoviews_git/holoviews/core/operation.py", line 121, in _apply
    ret = self._process(element, key)
  File "~/holoviews_git/holoviews/operation/datashader.py", line 437, in _process
    x, y, data, glyph = self.get_agg_data(element, category)
  File "~/holoviews_git/holoviews/operation/datashader.py", line 327, in get_agg_data
    for d in (x, y)):
  File "~/holoviews_git/holoviews/operation/datashader.py", line 327, in <genexpr>
    for d in (x, y)):
  File "~/anaconda/envs/pyviz/lib/python3.6/site-packages/dask/array/core.py", line 1383, in __getitem__
    dsk, chunks = slice_array(out, self.name, self.chunks, index2)
  File "~/anaconda/envs/pyviz/lib/python3.6/site-packages/dask/array/slicing.py", line 158, in slice_array
    dsk_out, bd_out = slice_with_newaxes(out_name, in_name, blockdims, index)
  File "~/anaconda/envs/pyviz/lib/python3.6/site-packages/dask/array/slicing.py", line 180, in slice_with_newaxes
    dsk, blockdims2 = slice_wrap_lists(out_name, in_name, blockdims, index2)
  File "~/anaconda/envs/pyviz/lib/python3.6/site-packages/dask/array/slicing.py", line 235, in slice_wrap_lists
    return slice_slices_and_integers(out_name, in_name, blockdims, index)
  File "~/anaconda/envs/pyviz/lib/python3.6/site-packages/dask/array/slicing.py", line 280, in slice_slices_and_integers
    raise ValueError("Arrays chunk sizes are unknown: %s", shape)
ValueError: ('Arrays chunk sizes are unknown: %s', (nan,))
```

**Comment by jbednar** [comment]
The same issue happens on the last two cells of examples/topics/census.ipynb from datashader, so it's not specific to bokeh server.  But it does seem specific to HoloViews or Bokeh, because bare Datashader rendering works fine (all the images before the last two cells of census.ipynb).

**Comment by philippjfr** [comment]
This is a regression introduced in the recent PR to support cftime types.

**Comment by philippjfr** [comment]
Fixed in https://github.com/ioam/holoviews/pull/3297

**Comment by philippjfr** [comment]
Fix was merged.

**Comment by jbednar** [comment]
Thanks!!
