### ISSUE TITLE
Pin more dependencies

### ISSUE THREAD

**Issue by ceball** [holoviz/holoviz#25]
The daily build passes and fails as dependencies move around underneath us. We should pin more dependencies, and update on something more like a monthly schedule. (We could still have a build using the latest versions of things, so we know what issues are coming.)

**Comment by ceball** [comment]
Haven't used conda env create on macos for pyviz for a while. I just noticed this so thought I'd record it:

```
$ conda env create
Solving environment: | 
Warning: 2 possible package resolutions (only showing differing packages):
  - defaults::gdal-2.2.2-py36hd505dc6_1, defaults::hdf5-1.10.1-ha036c08_1, defaults::kealib-1.4.7-hc1e10f3_5, defaults::libgdal-2.2.4-h390fe88_1, defaults::libnetcdf-4.4.1.1-hdf03fd4_8, defaults::netcdf4-1.3.1-py36hdbd7e57_2
  - defaults::gdal-2.2.4-py36h1702cab_1, defaults::hdf5-1.8.18-h017327d_1, defaults::kealib-1.4.7-haa18932_5, defaults::libgdal-2.2.4-h2fbb439_1, defaults::libnetcdf-4.4.1.1-h1d6afd8_8, defaults::netcdf4-1.3.1-py36h8ec8d5ddone
```

**Comment by brianmapes** [comment]
Here is a failure:  
short answer: ModuleNotFoundError: No module named 'pyct'

bash-3.2$ pip install pyviz

Collecting pyviz
  Using cached https://files.pythonhosted.org/packages/85/da/dff6fcd9faf46156473487a2a83f53bde07cd15f89a545c4f26d81055d91/pyviz-0.10.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/_l/h12pwyfd18g71lb_2xh4_0240000gr/T/pip-install-60o23yzs/pyviz/setup.py", line 4, in <module>
        import pyct.build
    ModuleNotFoundError: No module named 'pyct'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/_l/h12pwyfd18g71lb_2xh4_0240000gr/T/pip-install-60o23yzs/pyviz/

**Comment by whyboris** [comment]
Confirming: today when I tried `pip install pyviz` I got an error about `pyct`
```
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/32/pqw73fv945dcd6n_g619n7f8c_tzhw/T/pip-install-ew7cnimz/pyviz/setup.py", line 4, in <module>
        import pyct.build
    ModuleNotFoundError: No module named 'pyct'
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/32/pqw73fv945dcd6n_g619n7f8c_tzhw/T/pip-install-ew7cnimz/pyviz/
```
Solved with `pip install pyct`

**Comment by whyboris** [comment]
Confirming, after installing `pyct` with `pip install pyct` I got another error with `pip install pyviz` about `GEOS`
```
  ERROR: Complete output from command /Library/Frameworks/Python.framework/Versions/3.7/bin/python3.7 /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /var/folders/32/pqw73fv945dcd6n_g619n7f8c_tzhw/T/tmp71rz824n:
  ERROR: setup.py:171: UserWarning: Unable to determine GEOS version. Ensure you have 3.3.3 or later installed, or installation may fail.
    '.'.join(str(v) for v in GEOS_MIN_VERSION), ))
  Proj 4.9.0 must be installed.
  ----------------------------------------
ERROR: Command "/Library/Frameworks/Python.framework/Versions/3.7/bin/python3.7 /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /var/folders/32/pqw73fv945dcd6n_g619n7f8c_tzhw/T/tmp71rz824n" failed with error code 1 in /private/var/folders/32/pqw73fv945dcd6n_g619n7f8c_tzhw/T/pip-install-kejwy8wz/cartopy
```
Solved (on _Mac_) with `brew install geos`

Ran `pip install pyviz` again but got this error:
```
  ERROR: Complete output from command /Library/Frameworks/Python.framework/Versions/3.7/bin/python3.7 /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_buil
d_wheel /var/folders/32/pqw73fv945dcd6n_g619n7f8c_tzhw/T/tmp1mjb2av6:
  ERROR: Proj 4.9.0 must be installed.
  ----------------------------------------
ERROR: Command "/Library/Frameworks/Python.framework/Versions/3.7/bin/python3.7 /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /var/folders/3
2/pqw73fv945dcd6n_g619n7f8c_tzhw/T/tmp1mjb2av6" failed with error code 1 in /private/var/folders/32/pqw73fv945dcd6n_g619n7f8c_tzhw/T/pip-install-31a97o80/cartopy
```
Solved with `brew install proj`

**Comment by whyboris** [comment]
After solving the above problems, `pip install pyviz` fails due to `cartopy`:
```
#error 'To use the proj_api.h you must define the macro ACCEPT_USE_OF_DEPRECATED_PROJ_API_H'
```
Waiting for this PR to merge so the installation can proceed: https://github.com/SciTools/cartopy/pull/1289

**Comment by jbednar** [comment]
The new versions do pin more dependencies; closing.
