### ISSUE TITLE
Tutorial files down't download when following instruction on tutorial guide

### ISSUE THREAD

**Issue by Pigankle** [holoviz/holoviz#337]
This is probably not a bug in holoviz itself, but the instructions for installing the tutorial aren't working.

I am trying to install the tutorial files.  I normally use python 3.10 or 3.11 depending on package availability, but I wante to try the tutorial so I followed the instructions here: https://holoviz.org/tutorial/Setup.html
These two commands worked fine:
```
conda create -n project "anaconda-project>=0.11"
conda activate project
```

Then I try to get the tutorial files: 
`anaconda-project.exe download pyviz/holoviz_tutorial`

and it fails (full error message below)

Is there a direct link to download the files?

#### ALL software version info
Windows11.  Powershell
python 3.6.15  (! - that's what `conda create - project` downloaded and setup)

#### Description of expected behavior and the observed behavior
Expected tutorial files to be downloaded.
That didn't happen.

#### Complete, minimal, self-contained example code that reproduces the issue
(In powershell, I issue this command, per tutorial 
```
anaconda-project.exe download pyviz/holoviz_tutorial
```

#### Stack traceback and/or browser JavaScript console output
```
C:\Users\junea\miniconda3\envs\project\lib\site-packages\binstar_client\utils\config.py:186: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(fd)
Using Anaconda API: https://api.anaconda.org
C:\Users\junea\miniconda3\envs\project\lib\site-packages\requests\packages\urllib3\connectionpool.py:843: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
C:\Users\junea\miniconda3\envs\project\lib\site-packages\requests\packages\urllib3\connectionpool.py:843: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
C:\Users\junea\miniconda3\envs\project\lib\site-packages\requests\packages\urllib3\connectionpool.py:843: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
An unexpected error occurred, most likely a bug in anaconda-project.
    (The error was: AttributeError: __enter__)
Details about the error were saved to C:\Users\junea\AppData\Local\Temp\bug_details_anaconda-project_2022-11-18_018g8gml.txt
```

**Comment by maximlt** [comment]
Hi @Pigankle,

Thanks for reporting the issue you encountered. We'll need a little bit more information to try to fix it.

- Could you report the output of the `conda info` command?
- Could you activate the project environment with `conda activate project` and report the output of the `conda list` command?
- Could you report the content of the `bug_details_anaconda-project_2022-11-18_018g8gml.txt` file?

I'm pretty surprised to see you got Python 3.6 in your *project* environment.

**Comment by Pigankle** [comment]
```
(base) PS C:\Users\junea\Computery Stuff> python --version
Python 3.10.6

(base) PS C:\Users\junea\Computery Stuff> conda activate project

(project) PS C:\Users\junea\Computery Stuff> conda info

     active environment : project
    active env location : C:\Users\junea\miniconda3\envs\project
            shell level : 2
       user config file : C:\Users\junea\.condarc
 populated config files : C:\Users\junea\.condarc
          conda version : 22.9.0
    conda-build version : not installed
         python version : 3.10.6.final.0
       virtual packages : __cuda=11.6=0
                          __win=0=0
                          __archspec=1=x86_64
       base environment : C:\Users\junea\miniconda3  (writable)
      conda av data dir : C:\Users\junea\miniconda3\etc\conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\junea\miniconda3\pkgs
                          C:\Users\junea\.conda\pkgs
                          C:\Users\junea\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\junea\miniconda3\envs
                          C:\Users\junea\.conda\envs
                          C:\Users\junea\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/22.9.0 requests/2.28.1 CPython/3.10.6 Windows/10 Windows/10.0.22623
          administrator : False
             netrc file : None
           offline mode : False

(project) PS C:\Users\junea\Computery Stuff> conda list
# packages in environment at C:\Users\junea\miniconda3\envs\project:
#
# Name                    Version                   Build  Channel
anaconda-client           1.6.3                    py36_0    conda-forge
anaconda-project          0.11.1             pyhd8ed1ab_0    conda-forge
bleach                    4.1.0                    pypi_0    pypi
bokeh                     2.3.3                    pypi_0    pypi
certifi                   2020.6.20          pyhd3eb1b0_3
clyent                    1.2.2                      py_1    conda-forge
colorama                  0.4.5              pyhd8ed1ab_0    conda-forge
colorcet                  3.0.1                    pypi_0    pypi
conda-pack                0.7.0              pyh6c4a22f_0    conda-forge
holoviews                 1.14.9                   pypi_0    pypi
hvplot                    0.8.1                    pypi_0    pypi
importlib-metadata        4.8.3                    pypi_0    pypi
importlib-resources       5.4.0                    pypi_0    pypi
jinja2                    2.11.3             pyhd8ed1ab_2    conda-forge
markdown                  3.3.7                    pypi_0    pypi
markupsafe                1.1.1            py36h68aa20f_3    conda-forge
numpy                     1.19.5                   pypi_0    pypi
packaging                 21.3                     pypi_0    pypi
pandas                    1.1.5                    pypi_0    pypi
panel                     0.12.1                   pypi_0    pypi
param                     1.12.2                   pypi_0    pypi
pillow                    8.4.0                    pypi_0    pypi
pip                       21.2.4             pyhd8ed1ab_0    conda-forge
pyct                      0.4.8                    pypi_0    pypi
pyparsing                 3.0.9                    pypi_0    pypi
python                    3.6.15          h39d44d4_0_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python_abi                3.6                     2_cp36m    conda-forge
pytz                      2022.6             pyhd8ed1ab_0    conda-forge
pyviz-comms               2.2.1                    pypi_0    pypi
pyyaml                    5.4.1            py36h68aa20f_1    conda-forge
requests                  2.12.5                   py36_0    conda-forge
ruamel_yaml               0.15.80         py36h68aa20f_1004    conda-forge
setuptools                49.6.0           py36ha15d459_3    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
tornado                   6.1              py36h68aa20f_1    conda-forge
tqdm                      4.64.1             pyhd8ed1ab_0    conda-forge
typing-extensions         4.1.1                    pypi_0    pypi
ucrt                      10.0.22621.0         h57928b3_0    conda-forge
vc                        14.3                 h3d8a991_9    conda-forge
vs2015_runtime            14.32.31332          h1d6e394_9    conda-forge
webencodings              0.5.1                    pypi_0    pypi
wheel                     0.34.2                   py36_0    conda-forge
wincertstore              0.2             pyhd8ed1ab_1009    conda-forge
yaml                      0.2.5                h8ffe710_2    conda-forge
zipp                      3.6.0                    pypi_0    pypi
```
and
```
(project) PS C:\Users\junea\Computery Stuff> python --version
Python 3.6.15

```

Bug Details File Attached:
[bug_details_anaconda-project_2022-11-25_w7d7fvmd.txt](https://github.com/holoviz/holoviz/files/10094726/bug_details_anaconda-project_2022-11-25_w7d7fvmd.txt)

**Comment by Pigankle** [comment]
And in case you were wanting conda list from my base environment:
```
(base) PS C:\Users\junea\Computery Stuff> conda list
# packages in environment at C:\Users\junea\miniconda3:
#
# Name                    Version                   Build  Channel
arcade                    2.6.16                   pypi_0    pypi
asttokens                 2.1.0              pyhd8ed1ab_0    conda-forge
attrs                     22.1.0                   pypi_0    pypi
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.6.4              pyhd8ed1ab_0    conda-forge
brotlipy                  0.7.0           py310h8d17308_1005    conda-forge
bzip2                     1.0.8                h8ffe710_4    conda-forge
ca-certificates           2022.9.24            h5b45459_0    conda-forge
certifi                   2022.9.24          pyhd8ed1ab_0    conda-forge
cffi                      1.15.1          py310h628cb3f_2    conda-forge
charset-normalizer        2.1.1              pyhd8ed1ab_0    conda-forge
colorama                  0.4.6              pyhd8ed1ab_0    conda-forge
conda                     22.9.0          py310h5588dad_2    conda-forge
conda-package-handling    1.9.0           py310h635b8f1_1    conda-forge
console_shortcut          0.1.1                         4
contourpy                 1.0.6                    pypi_0    pypi
cryptography              38.0.3          py310h6e82f81_0    conda-forge
cycler                    0.11.0                   pypi_0    pypi
debugpy                   1.6.3           py310h00ffb61_1    conda-forge
decorator                 5.1.1              pyhd8ed1ab_0    conda-forge
entrypoints               0.4                pyhd8ed1ab_0    conda-forge
executing                 1.2.0              pyhd8ed1ab_0    conda-forge
fonttools                 4.38.0                   pypi_0    pypi
idna                      3.4                pyhd8ed1ab_0    conda-forge
ipykernel                 6.17.1             pyh025b116_0    conda-forge
ipython                   8.6.0              pyh08f2357_1    conda-forge
jedi                      0.18.1             pyhd8ed1ab_2    conda-forge
jupyter_client            7.4.7              pyhd8ed1ab_0    conda-forge
jupyter_core              5.0.0           py310h5588dad_0    conda-forge
kiwisolver                1.4.4                    pypi_0    pypi
libffi                    3.4.2                h8ffe710_5    conda-forge
libsodium                 1.0.18               h8d14728_1    conda-forge
libsqlite                 3.40.0               hcfcfb64_0    conda-forge
libzlib                   1.2.13               hcfcfb64_4    conda-forge
matplotlib                3.6.2                    pypi_0    pypi
matplotlib-inline         0.1.6              pyhd8ed1ab_0    conda-forge
menuinst                  1.4.19          py310h5588dad_1    conda-forge
nest-asyncio              1.5.6              pyhd8ed1ab_0    conda-forge
numpy                     1.23.4                   pypi_0    pypi
openssl                   3.0.7                hcfcfb64_0    conda-forge
packaging                 21.3               pyhd8ed1ab_0    conda-forge
parso                     0.8.3              pyhd8ed1ab_0    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pillow                    9.1.1                    pypi_0    pypi
pip                       22.3.1             pyhd8ed1ab_0    conda-forge
platformdirs              2.5.2              pyhd8ed1ab_1    conda-forge
powershell_shortcut       0.0.1                         3
prompt-toolkit            3.0.32             pyha770c72_0    conda-forge
psutil                    5.9.4           py310h8d17308_0    conda-forge
pure_eval                 0.2.2              pyhd8ed1ab_0    conda-forge
pycosat                   0.6.4           py310h8d17308_1    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pyglet                    2.0.dev23                pypi_0    pypi
pygments                  2.13.0             pyhd8ed1ab_0    conda-forge
pymunk                    6.2.1                    pypi_0    pypi
pyopenssl                 22.1.0             pyhd8ed1ab_0    conda-forge
pyparsing                 3.0.9              pyhd8ed1ab_0    conda-forge
pysocks                   1.7.1              pyh0701188_6    conda-forge
python                    3.10.6          hcf16a7b_0_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python_abi                3.10                    2_cp310    conda-forge
pytiled-parser            2.2.0                    pypi_0    pypi
pywin32                   304             py310h00ffb61_2    conda-forge
pyzmq                     24.0.1          py310hcd737a0_1    conda-forge
requests                  2.28.1             pyhd8ed1ab_1    conda-forge
ruamel_yaml               0.15.80         py310h8d17308_1008    conda-forge
setuptools                65.5.1             pyhd8ed1ab_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
stack_data                0.6.1              pyhd8ed1ab_0    conda-forge
tk                        8.6.12               h8ffe710_0    conda-forge
toolz                     0.12.0             pyhd8ed1ab_0    conda-forge
tornado                   6.2             py310h8d17308_1    conda-forge
touch                     2020.12.3                pypi_0    pypi
tqdm                      4.64.1             pyhd8ed1ab_0    conda-forge
traitlets                 5.5.0              pyhd8ed1ab_0    conda-forge
typing-extensions         4.4.0                    pypi_0    pypi
tzdata                    2022f                h191b570_0    conda-forge
ucrt                      10.0.22621.0         h57928b3_0    conda-forge
urllib3                   1.26.11            pyhd8ed1ab_0    conda-forge
values                    2020.12.3                pypi_0    pypi
vc                        14.3                 h3d8a991_9    conda-forge
vs2015_runtime            14.32.31332          h1d6e394_9    conda-forge
wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
wheel                     0.38.4             pyhd8ed1ab_0    conda-forge
win_inet_pton             1.1.0              pyhd8ed1ab_6    conda-forge
xz                        5.2.6                h8d14728_0    conda-forge
yaml                      0.2.5                h8ffe710_2    conda-forge
zeromq                    4.3.4                h0e60522_1    conda-forge
```

**Comment by Pigankle** [comment]
...and just to make it easier to browse the bug details file, here's the content thereof:
```
Bug details for anaconda-project error on 2022-11-25

sys.argv: ['C:\\Users\\junea\\miniconda3\\envs\\project\\Scripts\\anaconda-project', 'download', 'pyviz/holoviz_tutorial']

{'version': '0.11.1'}

Traceback (most recent call last):

  File "C:\Users\junea\miniconda3\envs\project\lib\site-packages\anaconda_project\internal\cli\bug_handler.py", line 31, in handle_bugs
    return main_func()

  File "C:\Users\junea\miniconda3\envs\project\lib\site-packages\anaconda_project\internal\cli\main.py", line 435, in _main_without_bug_handler
    return _parse_args_and_run_subcommand(sys.argv)

  File "C:\Users\junea\miniconda3\envs\project\lib\site-packages\anaconda_project\internal\cli\main.py", line 427, in _parse_args_and_run_subcommand
    return args.main(args)

  File "C:\Users\junea\miniconda3\envs\project\lib\site-packages\anaconda_project\internal\cli\download.py", line 44, in main
    return download_command(args.project, not args.no_unpack, args.parent_dir, args.site, args.user, args.token)

  File "C:\Users\junea\miniconda3\envs\project\lib\site-packages\anaconda_project\internal\cli\download.py", line 33, in download_command
    token=token)

  File "C:\Users\junea\miniconda3\envs\project\lib\site-packages\anaconda_project\project_ops.py", line 1825, in download
    token=token)

  File "C:\Users\junea\miniconda3\envs\project\lib\site-packages\anaconda_project\client.py", line 243, in _download
    fn = client.download(project, project_dir, parent_dir)

  File "C:\Users\junea\miniconda3\envs\project\lib\site-packages\anaconda_project\client.py", line 181, in download
    with self._api.session.get(url, data=data, headers=headers, stream=True) as res:

AttributeError: __enter__

```

**Comment by maximlt** [comment]
Hi! Thanks for the detailed report, that's very helpful. I'm very surprised to see you have packages from PyPI on your `project` environment.

Could you try the following?

- `conda create -n project2 "anaconda-project>=0.11"`
- `conda activate project2`
- `conda list` to check you have no packages from PyPi and a more recent version of Python (3.10 probably). If not, stop there and report that as I'll need to dig in into that.

When you run anaconda-project, I don't think you need to suffix it with `.exe`.

**Comment by Pigankle** [comment]
EDIT:  I split up this reply and added some comments just so I can follow my own thread more easily.  These are all consecutive commands and outputs, with no other chicanery in between.

```
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Install the latest PowerShell for new features and improvements! https://aka.ms/PSWindows

Loading personal and system profiles took 1274ms.
(base) PS C:\Users\junea> conda list
# packages in environment at C:\Users\junea\miniconda3:
#
# Name                    Version                   Build  Channel
arcade                    2.6.16                   pypi_0    pypi
asttokens                 2.1.0              pyhd8ed1ab_0    conda-forge
attrs                     22.1.0                   pypi_0    pypi
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.6.4              pyhd8ed1ab_0    conda-forge
brotlipy                  0.7.0           py310h8d17308_1005    conda-forge
bzip2                     1.0.8                h8ffe710_4    conda-forge
ca-certificates           2022.9.24            h5b45459_0    conda-forge
certifi                   2022.9.24          pyhd8ed1ab_0    conda-forge
cffi                      1.15.1          py310h628cb3f_2    conda-forge
charset-normalizer        2.1.1              pyhd8ed1ab_0    conda-forge
colorama                  0.4.6              pyhd8ed1ab_0    conda-forge
conda                     22.9.0          py310h5588dad_2    conda-forge
conda-package-handling    1.9.0           py310h635b8f1_1    conda-forge
console_shortcut          0.1.1                         4
contourpy                 1.0.6                    pypi_0    pypi
cryptography              38.0.3          py310h6e82f81_0    conda-forge
cycler                    0.11.0                   pypi_0    pypi
debugpy                   1.6.3           py310h00ffb61_1    conda-forge
decorator                 5.1.1              pyhd8ed1ab_0    conda-forge
entrypoints               0.4                pyhd8ed1ab_0    conda-forge
executing                 1.2.0              pyhd8ed1ab_0    conda-forge
fonttools                 4.38.0                   pypi_0    pypi
idna                      3.4                pyhd8ed1ab_0    conda-forge
ipykernel                 6.17.1             pyh025b116_0    conda-forge
ipython                   8.6.0              pyh08f2357_1    conda-forge
jedi                      0.18.1             pyhd8ed1ab_2    conda-forge
jupyter_client            7.4.7              pyhd8ed1ab_0    conda-forge
jupyter_core              5.0.0           py310h5588dad_0    conda-forge
kiwisolver                1.4.4                    pypi_0    pypi
libffi                    3.4.2                h8ffe710_5    conda-forge
libsodium                 1.0.18               h8d14728_1    conda-forge
libsqlite                 3.40.0               hcfcfb64_0    conda-forge
libzlib                   1.2.13               hcfcfb64_4    conda-forge
matplotlib                3.6.2                    pypi_0    pypi
matplotlib-inline         0.1.6              pyhd8ed1ab_0    conda-forge
menuinst                  1.4.19          py310h5588dad_1    conda-forge
nest-asyncio              1.5.6              pyhd8ed1ab_0    conda-forge
numpy                     1.23.4                   pypi_0    pypi
openssl                   3.0.7                hcfcfb64_0    conda-forge
packaging                 21.3               pyhd8ed1ab_0    conda-forge
parso                     0.8.3              pyhd8ed1ab_0    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pillow                    9.1.1                    pypi_0    pypi
pip                       22.3.1             pyhd8ed1ab_0    conda-forge
platformdirs              2.5.2              pyhd8ed1ab_1    conda-forge
powershell_shortcut       0.0.1                         3
prompt-toolkit            3.0.32             pyha770c72_0    conda-forge
psutil                    5.9.4           py310h8d17308_0    conda-forge
pure_eval                 0.2.2              pyhd8ed1ab_0    conda-forge
pycosat                   0.6.4           py310h8d17308_1    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pyglet                    2.0.dev23                pypi_0    pypi
pygments                  2.13.0             pyhd8ed1ab_0    conda-forge
pymunk                    6.2.1                    pypi_0    pypi
pyopenssl                 22.1.0             pyhd8ed1ab_0    conda-forge
pyparsing                 3.0.9              pyhd8ed1ab_0    conda-forge
pysocks                   1.7.1              pyh0701188_6    conda-forge
python                    3.10.6          hcf16a7b_0_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python_abi                3.10                    2_cp310    conda-forge
pytiled-parser            2.2.0                    pypi_0    pypi
pywin32                   304             py310h00ffb61_2    conda-forge
pyzmq                     24.0.1          py310hcd737a0_1    conda-forge
requests                  2.28.1             pyhd8ed1ab_1    conda-forge
ruamel_yaml               0.15.80         py310h8d17308_1008    conda-forge
setuptools                65.5.1             pyhd8ed1ab_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
stack_data                0.6.1              pyhd8ed1ab_0    conda-forge
tk                        8.6.12               h8ffe710_0    conda-forge
toolz                     0.12.0             pyhd8ed1ab_0    conda-forge
tornado                   6.2             py310h8d17308_1    conda-forge
touch                     2020.12.3                pypi_0    pypi
tqdm                      4.64.1             pyhd8ed1ab_0    conda-forge
traitlets                 5.5.0              pyhd8ed1ab_0    conda-forge
typing-extensions         4.4.0                    pypi_0    pypi
tzdata                    2022f                h191b570_0    conda-forge
ucrt                      10.0.22621.0         h57928b3_0    conda-forge
urllib3                   1.26.11            pyhd8ed1ab_0    conda-forge
values                    2020.12.3                pypi_0    pypi
vc                        14.3                 h3d8a991_9    conda-forge
vs2015_runtime            14.32.31332          h1d6e394_9    conda-forge
wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
wheel                     0.38.4             pyhd8ed1ab_0    conda-forge
win_inet_pton             1.1.0              pyhd8ed1ab_6    conda-forge
xz                        5.2.6                h8d14728_0    conda-forge
yaml                      0.2.5                h8ffe710_2    conda-forge
zeromq                    4.3.4                h0e60522_1    conda-forge

```
...yeah - I know I have been putting too much into my base environment.  Anyways, with that starting point, I create a new project:

```

(base) PS C:\Users\junea> conda create -n project2 "anaconda-project>=0.11"
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: C:\Users\junea\miniconda3\envs\project2

  added / updated specs:
    - anaconda-project[version='>=0.11']


The following NEW packages will be INSTALLED:

  anaconda-client    conda-forge/win-64::anaconda-client-1.6.3-py36_0 None
  anaconda-project   conda-forge/noarch::anaconda-project-0.11.1-pyhd8ed1ab_0 None
  certifi            pkgs/main/noarch::certifi-2020.6.20-pyhd3eb1b0_3 None
  clyent             conda-forge/noarch::clyent-1.2.2-py_1 None
  colorama           conda-forge/noarch::colorama-0.4.5-pyhd8ed1ab_0 None
  conda-pack         conda-forge/noarch::conda-pack-0.7.0-pyh6c4a22f_0 None
  jinja2             conda-forge/noarch::jinja2-2.11.3-pyhd8ed1ab_2 None
  markupsafe         conda-forge/win-64::markupsafe-1.1.1-py36h68aa20f_3 None
  pip                conda-forge/noarch::pip-21.2.4-pyhd8ed1ab_0 None
  python             conda-forge/win-64::python-3.6.15-h39d44d4_0_cpython None
  python-dateutil    conda-forge/noarch::python-dateutil-2.8.2-pyhd8ed1ab_0 None
  python_abi         conda-forge/win-64::python_abi-3.6-2_cp36m None
  pytz               conda-forge/noarch::pytz-2022.6-pyhd8ed1ab_0 None
  pyyaml             conda-forge/win-64::pyyaml-5.4.1-py36h68aa20f_1 None
  requests           conda-forge/win-64::requests-2.12.5-py36_0 None
  ruamel_yaml        conda-forge/win-64::ruamel_yaml-0.15.80-py36h68aa20f_1004 None
  setuptools         conda-forge/win-64::setuptools-49.6.0-py36ha15d459_3 None
  six                conda-forge/noarch::six-1.16.0-pyh6c4a22f_0 None
  tornado            conda-forge/win-64::tornado-6.1-py36h68aa20f_1 None
  tqdm               conda-forge/noarch::tqdm-4.64.1-pyhd8ed1ab_0 None
  ucrt               conda-forge/win-64::ucrt-10.0.22621.0-h57928b3_0 None
  vc                 conda-forge/win-64::vc-14.3-h3d8a991_9 None
  vs2015_runtime     conda-forge/win-64::vs2015_runtime-14.32.31332-h1d6e394_9 None
  wheel              conda-forge/win-64::wheel-0.34.2-py36_0 None
  wincertstore       conda-forge/noarch::wincertstore-0.2-pyhd8ed1ab_1009 None
  yaml               conda-forge/win-64::yaml-0.2.5-h8ffe710_2 None


Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate project2
#
# To deactivate an active environment, use
#
#     $ conda deactivate

Retrieving notices: ...working... done

```
Activate the new project and check what's there:
```

(base) PS C:\Users\junea> conda activate project2
(project2) PS C:\Users\junea> conda list
# packages in environment at C:\Users\junea\miniconda3\envs\project2:
#
# Name                    Version                   Build  Channel
anaconda-client           1.6.3                    py36_0    conda-forge
anaconda-project          0.11.1             pyhd8ed1ab_0    conda-forge
certifi                   2020.6.20          pyhd3eb1b0_3
clyent                    1.2.2                      py_1    conda-forge
colorama                  0.4.5              pyhd8ed1ab_0    conda-forge
conda-pack                0.7.0              pyh6c4a22f_0    conda-forge
jinja2                    2.11.3             pyhd8ed1ab_2    conda-forge
markupsafe                1.1.1            py36h68aa20f_3    conda-forge
pip                       21.2.4             pyhd8ed1ab_0    conda-forge
python                    3.6.15          h39d44d4_0_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python_abi                3.6                     2_cp36m    conda-forge
pytz                      2022.6             pyhd8ed1ab_0    conda-forge
pyyaml                    5.4.1            py36h68aa20f_1    conda-forge
requests                  2.12.5                   py36_0    conda-forge
ruamel_yaml               0.15.80         py36h68aa20f_1004    conda-forge
setuptools                49.6.0           py36ha15d459_3    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
tornado                   6.1              py36h68aa20f_1    conda-forge
tqdm                      4.64.1             pyhd8ed1ab_0    conda-forge
ucrt                      10.0.22621.0         h57928b3_0    conda-forge
vc                        14.3                 h3d8a991_9    conda-forge
vs2015_runtime            14.32.31332          h1d6e394_9    conda-forge
wheel                     0.34.2                   py36_0    conda-forge
wincertstore              0.2             pyhd8ed1ab_1009    conda-forge
yaml                      0.2.5                h8ffe710_2    conda-forge
```

Then, when I try to download the tutorial, the process quits almost immediately with the feedback below:
```
(project2) PS C:\Users\junea> anaconda-project download pyviz/holoviz_tutorial
C:\Users\junea\miniconda3\envs\project2\lib\site-packages\binstar_client\utils\config.py:186: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(fd)
Using Anaconda API: https://api.anaconda.org
C:\Users\junea\miniconda3\envs\project2\lib\site-packages\requests\packages\urllib3\connectionpool.py:843: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
C:\Users\junea\miniconda3\envs\project2\lib\site-packages\requests\packages\urllib3\connectionpool.py:843: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
C:\Users\junea\miniconda3\envs\project2\lib\site-packages\requests\packages\urllib3\connectionpool.py:843: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
An unexpected error occurred, most likely a bug in anaconda-project.
    (The error was: AttributeError: __enter__)
Details about the error were saved to C:\Users\junea\AppData\Local\Temp\bug_details_anaconda-project_2022-11-25_rak9ksox.txt
(project2) PS C:\Users\junea>
```

**Comment by maximlt** [comment]
Ok thanks for that again, that confirms that you can reproduce the issue and that you indeed get Python 3.6 installed when you run the command to create the project environment.

Another thing I'd like to ask you is to run `conda config --show-sources` from your base environment. It should display your `.condarc` configuration which may indeed affect what gets installed. Once you've reported that, I'll take all that information with me and ask internally (I'm working at Anaconda) how to debug that.

For what it's worth, on my machine running on MacOS I cannot reproduce the issue, I get Python 3.10 installed and `anaconda-project download pyviz/holoviz_tutorial` runs without any issue.

**Comment by Pigankle** [comment]
```
(pythonConda3.10) PS C:\Users\junea> conda activate base
(base) PS C:\Users\junea> conda config --show-sources
==> C:\Users\junea\.condarc <==
default_python: None
channels:
  - conda-forge
  - defaults

(base) PS C:\Users\junea>
   ```

and same in the   project environment (probably it is always the same? ... but just in case):
```
(project2) PS C:\Users\junea> conda config --show-sources
==> C:\Users\junea\.condarc <==
default_python: None
channels:
  - conda-forge
  - defaults

(project2) PS C:\Users\junea>
```

FWIW - I also have a 2012 MacBookPro and I can't get 3.10 to run at all.  Oh well.

Is there any other way to download the tutorial files in the meantime?
