### ISSUE TITLE
Error installing examples

### ISSUE THREAD

**Issue by larrywanzer** [holoviz/holoviz#37]
Not sure if I'm somehow doing something wrong, but following the steps on pyviz.org for doing the setup is giving me an error on Step 3: Install the tutorials in your home directory.

When I execute the following command

`pyviz --install-examples pyviz-tutorial`

I get this error

pyviz --install-examples pyviz-tutorial
Downloading archive: 'https://github.com/pyviz/pyviz/archive/master.zip'
Download complete. Extracting
Traceback (most recent call last):
  File "/Users/lwanzer/miniconda3/bin/pyviz", line 11, in <module>
    load_entry_point('pyviz==0.9.3', 'console_scripts', 'pyviz')()
  File "/Users/lwanzer/miniconda3/lib/python3.6/site-packages/pyviz/cmd.py", line 99, in main
    install_examples(args.install_examples)
  File "/Users/lwanzer/miniconda3/lib/python3.6/site-packages/pyviz/cmd.py", line 67, in install_examples
    file_data = zf.read('{file_path}'.format(ref=ref, file_path=file_path))
  File "/Users/lwanzer/miniconda3/lib/python3.6/zipfile.py", line 1314, in read
    with self.open(name, "r", pwd) as fp:
  File "/Users/lwanzer/miniconda3/lib/python3.6/zipfile.py", line 1352, in open
    zinfo = self.getinfo(name)
  File "/Users/lwanzer/miniconda3/lib/python3.6/zipfile.py", line 1281, in getinfo
    'There is no item named %r in the archive' % name)
KeyError: "There is no item named 'pyviz-master/datasets.yml' in the archive"

**Comment by jbednar** [comment]
Thanks for being the guinea pig! The installer is looking for the list of downloads in the wrong place, but we've put a copy back where it's looking for now.
