### ISSUE TITLE
Can't download data with pyviz commandline

### ISSUE THREAD

**Issue by AllanLRH** [holoviz/holoviz#87]
I think this says it all.

```
$ pyviz --download-sample-data pyviz-tutorial/data
Traceback (most recent call last):
  File "/Users/allan/homeInstalled/miniconda3/envs/pvz/bin/pyviz", line 5, in <module>
    from pyviz.cmd import main
  File "/Users/allan/homeInstalled/miniconda3/envs/pvz/lib/python3.6/site-packages/pyviz/__init__.py", line 10, in <module>
    import parambokeh as pb                                  # noqa (API import)
  File "/Users/allan/homeInstalled/miniconda3/envs/pvz/lib/python3.6/site-packages/parambokeh/__init__.py", line 11, in <module>
    from bokeh.document import Document
  File "/Users/allan/homeInstalled/miniconda3/envs/pvz/lib/python3.6/site-packages/bokeh/document/__init__.py", line 7, in <module>
    from .document import Document ; Document
  File "/Users/allan/homeInstalled/miniconda3/envs/pvz/lib/python3.6/site-packages/bokeh/document/document.py", line 35, in <module>
    from ..core.templates import FILE
  File "/Users/allan/homeInstalled/miniconda3/envs/pvz/lib/python3.6/site-packages/bokeh/core/templates.py", line 34, in <module>
    _env = get_env()
  File "/Users/allan/homeInstalled/miniconda3/envs/pvz/lib/python3.6/site-packages/bokeh/core/templates.py", line 31, in get_env
    return Environment(loader=PackageLoader('bokeh.core', '_templates'))
  File "/Users/allan/homeInstalled/miniconda3/envs/pvz/lib/python3.6/site-packages/jinja2/loaders.py", line 222, in __init__
    from pkg_resources import DefaultProvider, ResourceManager, \
ModuleNotFoundError: No module named 'pkg_resources'
```

I've made a clean install in a new conda environment, using Python 3.6. This part works though:
```
$ conda create --name pvz python=3.6 --yes
$ source activate pvz
$ conda install -c pyviz pyviz --yes
$ pyviz --install-examples pyviz-tutorial
```

**Comment by ceball** [comment]
@AllanLRH sorry not to have noticed this issue before now!

Also sorry that we don't yet have an issue template asking for some necessary information up front.

After activating the `pvz` environment, please could you provide the output of `conda list` and `conda info`?

(Also, could you confirm your platform is macos, and which version you're running?)

Thanks

**Comment by AllanLRH** [comment]
No problem :)
And yes, I'm using MacOS High Sierra (10.13.6), which is the newest stable version.

<details>
  <summary>Click to expand the listing of the requested command line outputs</summary>

```
(pvz) ❯ conda list
# packages in environment at /Users/allan/homeInstalled/miniconda3/envs/pvz:
#
appnope                   0.1.0            py36hf537a9a_0
atomicwrites              1.1.5                    py36_0
attrs                     18.1.0                   py36_0
blas                      1.0                         mkl
bokeh                     0.13.0                   py36_0
bzip2                     1.0.6                h1de35cc_5
ca-certificates           2018.03.07                    0
cairo                     1.14.12              hc4e6be7_4
cartopy                   0.16.0           py36h9263bd1_0
cffi                      1.11.5           py36h342bebf_0
cftime                    1.0.0b1          py36h1d22016_0
click                     6.7              py36hec950be_0
click-plugins             1.0.3            py36hb58b8ed_0
cligj                     0.4.0            py36h479156e_0
cloudpickle               0.5.3                    py36_0
colorcet                  1.0.0                    py36_0
curl                      7.61.0               ha441bb4_0
cycler                    0.10.0           py36hfc81398_0
cython                    0.28.5           py36h0a44026_0
cytoolz                   0.9.0.1          py36h1de35cc_1
dask                      0.18.1                   py36_0
dask-core                 0.18.1                   py36_0
datashader                0.6.7                      py_0    pyviz
datashape                 0.5.4                    py36_1
dbus                      1.13.2               h760590f_1
decorator                 4.3.0                    py36_0
descartes                 1.1.0                    py36_0
distributed               1.22.1                   py36_0
entrypoints               0.2.3                    py36_2
expat                     2.2.5                hb8e80ba_0
fastparquet               0.1.5            py36h1de35cc_0
fiona                     1.7.12           py36h0dff353_0
fontconfig                2.13.0               h5d5b041_1
freetype                  2.9.1                hb4e5f40_0
freexl                    1.0.5                h1de35cc_0
gdal                      2.2.4            py36h6440ff4_1
geopandas                 0.3.0                    py36_0
geos                      3.6.2                h5470d99_2
geoviews                  1.5.2                      py_0    pyviz
geoviews-core             1.5.2                      py_0    pyviz
gettext                   0.19.8.1             h15daf44_3
giflib                    5.1.4                h1de35cc_1
glib                      2.56.1               h35bc53a_0
hdf4                      4.2.13               h39711bb_2
hdf5                      1.10.2               hfa1e0ec_1
heapdict                  1.0.0                    py36_2
holoviews                 1.10.7                     py_0    pyviz
hvplot                    0.2.1                      py_0    pyviz
icu                       58.2                 h4b95b61_1
imageio                   2.3.0                    py36_0
intel-openmp              2018.0.3                      0
ipykernel                 4.8.2                    py36_0
ipython                   5.8.0                    py36_0
ipython_genutils          0.2.0            py36h241746c_0
ipywidgets                7.4.0                    py36_0
jinja2                    2.10                     py36_0
jpeg                      9b                   he5867d9_2
json-c                    0.13.1               h3efe00b_0
jsonschema                2.6.0            py36hb385e00_0
jupyter                   1.0.0                    py36_4
jupyter_client            5.2.3                    py36_0
jupyter_console           5.2.0                    py36_1
jupyter_core              4.4.0                    py36_0
kealib                    1.4.7                h40e48e4_6
kiwisolver                1.0.1            py36h0a44026_0
krb5                      1.16.1               h24a3359_6
libboost                  1.67.0               hebc422b_4
libcurl                   7.61.0               hf30b1f0_0
libcxx                    4.0.1                h579ed51_0
libcxxabi                 4.0.1                hebd6815_0
libdap4                   3.19.1               h3d3e54a_0
libedit                   3.1.20170329         hb402a30_2
libffi                    3.2.1                h475c297_4
libgdal                   2.2.4                h7b1ea53_1
libgfortran               3.0.1                h93005f0_2
libiconv                  1.15                 hdd342a3_7
libkml                    1.3.0                hbe12b63_4
libnetcdf                 4.6.1                h148f0bd_0
libpng                    1.6.34               he12f830_0
libpq                     10.4                 hf30b1f0_0
libsodium                 1.0.16               h3efe00b_0
libspatialindex           1.8.5                h2c08c6b_2
libspatialite             4.3.0a              ha12ebda_19
libssh2                   1.8.0                h322a93b_4
libtiff                   4.0.9                hcb84e12_1
libuuid                   1.0.3                h6bb4b03_2
libxml2                   2.9.8                hab757c2_1
libxslt                   1.1.32               hb819dd2_0
llvmlite                  0.24.0           py36hc454e04_0
locket                    0.2.0            py36hca03003_1
lxml                      4.2.4            py36hef8c89e_0
markupsafe                1.0              py36h1de35cc_1
matplotlib                2.2.2            py36hbf02d85_2
mistune                   0.8.3            py36h1de35cc_1
mkl                       2018.0.3                      1
more-itertools            4.3.0                    py36_0
msgpack-python            0.5.6            py36h04f5b5a_1
multipledispatch          0.5.0                    py36_0
munch                     2.3.2                    py36_0
nbconvert                 4.2.0                    py36_0
nbformat                  4.4.0            py36h827af21_0
ncurses                   6.1                  h0a44026_0
netcdf4                   1.4.0            py36h08833f9_1
networkx                  2.1                      py36_0
notebook                  5.5.0                    py36_0
numba                     0.39.0           py36h6440ff4_0
numpy                     1.14.3           py36he6379a5_2
numpy-base                1.15.0           py36h8a80b8c_0
olefile                   0.45.1                   py36_0
openjpeg                  2.3.0                hb95cd4c_1
openssl                   1.0.2o               h1de35cc_1
owslib                    0.16.0                   py36_0
packaging                 17.1                     py36_0
pandas                    0.23.4           py36h6440ff4_0
param                     1.7.0                      py_0    pyviz
parambokeh                0.2.3                      py_0    pyviz
paramnb                   2.0.4                      py_0    pyviz
partd                     0.3.8            py36hf5c4cb8_0
pcre                      8.42                 h378b8a2_0
pexpect                   4.6.0                    py36_0
phantomjs                 2.1.1                         0    pyviz
pickleshare               0.7.4            py36hf512f8e_0
pillow                    5.2.0            py36hb68e598_0
pip                       18.0                      <pip>
pip                       10.0.1                   py36_0
pixman                    0.34.0               hca0a616_3
pluggy                    0.7.1                    py36_0
poppler                   0.65.0               ha097c24_1
poppler-data              0.4.9                         0
proj4                     5.0.1                h1de35cc_0
prompt_toolkit            1.0.15           py36haeda067_0
psutil                    5.4.6            py36h1de35cc_0
psycopg2                  2.7.5            py36hdbc3d79_0
ptyprocess                0.6.0                    py36_0
py                        1.5.4                    py36_0
pycparser                 2.18                     py36_1
pyct                      0.4.5                      py_0    pyviz
pyct-core                 0.4.5                      py_0    pyviz
pyepsg                    0.3.2                    py36_0
pygments                  2.2.0            py36h240cd3f_0
pyparsing                 2.2.0                    py36_1
pyproj                    1.9.5.1          py36h833a5d7_1
pyqt                      5.9.2            py36h655552a_0
pysal                     1.14.4.post1             py36_1
pyshp                     1.2.12                   py36_0
pytest                    3.7.1                    py36_0
python                    3.6.6                hc167b69_0
python-dateutil           2.7.3                    py36_0
python-snappy             0.5.2            py36h0a44026_0
pytz                      2018.5                   py36_0
pyviz                     0.9.11                     py_0    pyviz
pyviz_comms               0.5.0                      py_1    pyviz
pywavelets                0.5.2            py36h1d22016_2
pyyaml                    3.13             py36h1de35cc_0
pyzmq                     17.1.0           py36h1de35cc_0
qt                        5.9.6                h74ce4d9_0
qtconsole                 4.3.1            py36hd96c0ff_0
readline                  7.0                  hc1231fa_4
requests                  2.14.2                   py36_0
rise                      5.3.0                    py36_0    pyviz
rtree                     0.8.3                    py36_0
scikit-image              0.14.0           py36h0a44026_1
scipy                     1.1.0            py36hf1f7d93_0
selenium                  3.13.0           py36h1de35cc_0
send2trash                1.5.0                    py36_0
setuptools                27.2.0                   py36_0
shapely                   1.6.4            py36h20de77a_0
simplegeneric             0.8.1                    py36_2
sip                       4.19.8           py36h0a44026_0
six                       1.11.0                   py36_1
snappy                    1.1.7                he62c110_3
sortedcontainers          2.0.4                    py36_0
sqlalchemy                1.2.10           py36h1de35cc_0
sqlite                    3.24.0               ha441bb4_0
streamz                   0.3.0                    py36_0
tblib                     1.3.2            py36hda67792_0
terminado                 0.8.1                    py36_1
thrift                    0.11.0           py36h0a44026_0
tk                        8.6.7                h35a86e2_3
toolz                     0.9.0                    py36_0
tornado                   4.5.3                    py36_0
traitlets                 4.3.2            py36h65bd3ce_0
wcwidth                   0.1.7            py36h8c6ec74_0
wheel                     0.31.1                   py36_0
widgetsnbextension        3.4.0                    py36_0
xarray                    0.10.8                   py36_0
xerces-c                  3.2.1                h44e365a_0
xz                        5.2.4                h1de35cc_4
yaml                      0.1.7                hc338f04_2
zeromq                    4.2.5                h0a44026_0
zict                      0.1.3                    py36_0
zlib                      1.2.11               hf3cbc9b_2

~
(pvz) ❯ conda info
Current conda install:

               platform : osx-64
          conda version : 4.3.30
       conda is private : False
      conda-env version : 4.3.30
    conda-build version : not installed
         python version : 3.6.3.final.0
       requests version : 2.18.4
       root environment : /Users/allan/homeInstalled/miniconda3  (writable)
    default environment : /Users/allan/homeInstalled/miniconda3/envs/pvz
       envs directories : /Users/allan/homeInstalled/miniconda3/envs
                          /Users/allan/.conda/envs
          package cache : /Users/allan/homeInstalled/miniconda3/pkgs
                          /Users/allan/.conda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/main/osx-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/osx-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://conda.anaconda.org/ostrokach-forge/osx-64
                          https://conda.anaconda.org/ostrokach-forge/noarch
                          https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/intel/osx-64
                          https://conda.anaconda.org/intel/noarch
            config file : /Users/allan/.condarc
             netrc file : /Users/allan/.netrc
           offline mode : False
             user-agent : conda/4.3.30 requests/2.18.4 CPython/3.6.3 Darwin/17.7.0 OSX/10.13.6
                UID:GID : 501:20

(py36) ❯ cat ~/.condarc
channels:
  - defaults
  - ostrokach-forge
  - conda-forge
  - intel
```
</details>

**Comment by AllanLRH** [comment]
Sorry, forgot to run the `conda update conda` twice before installing. It works now 👍
